name: UCRA Commands

on:
  issue_comment:
    types: [created]
  pull_request_review_comment:
    types: [created]

jobs:
  handle-command:
    if: >
      contains(github.event.comment.body, '/deploy') ||
      contains(github.event.comment.body, '/seed')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      issues: write
      pull-requests: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Detect command
        id: cmd
        run: |
          BODY="${{ github.event.comment.body }}"
          if echo "$BODY" | grep -qi '^/deploy'; then
            echo "cmd=deploy" >> $GITHUB_OUTPUT
          elif echo "$BODY" | grep -qi '^/seed'; then
            echo "cmd=seed" >> $GITHUB_OUTPUT
          else
            echo "cmd=unknown" >> $GITHUB_OUTPUT
          fi

      # ---------- /seed ----------
      - name: Install deps (seed)
        if: steps.cmd.outputs.cmd == 'seed'
        run: |
          npm ci || npm i
      - name: Run seed
        if: steps.cmd.outputs.cmd == 'seed'
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
          FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
        run: |
          npx ts-node --compiler-options '{"module":"commonjs"}' scripts/seed.ts

      # ---------- /deploy ----------
      - name: Trigger Vercel Deploy Hook
        if: steps.cmd.outputs.cmd == 'deploy'
        run: |
          curl -s -X POST "${{ secrets.VERCEL_DEPLOY_HOOK_URL }}"

      # ---------- Report back ----------
      - name: Comment result
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const cmd = '${{ steps.cmd.outputs.cmd }}';
            const outcome = '${{ job.status }}';
            let msg = '';
            if (cmd === 'seed') {
              msg = outcome === 'success'
                ? '✅ **/seed** ejecutado: vendor y 12 productos creados.'
                : '❌ **/seed** falló. Mira logs en Actions.';
            } else if (cmd === 'deploy') {
              msg = outcome === 'success'
                ? '✅ **/deploy** disparado. Vercel está construyendo.'
                : '❌ **/deploy** falló. Revisa el Deploy Hook/Logs.';
            } else {
              msg = '🤖 Comando no reconocido.';
            }
            github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue ? context.payload.issue.number : context.payload.pull_request.number,
              body: msg
            });
